### PR TITLE
delete 'import git.py'

### PR DESCRIPTION
**Pull request by dnadeau4**

### CODE REVIEW

**Review by doutriaux1 — CHANGES_REQUESTED** [review]
@dnadeau4 you probably want to remove https://github.com/CDAT/cdms/blob/master/setup.py#L25-L45 if you do this.

**Review by dnadeau4 — COMMENTED** [review]
done

**Review by zshaheen — APPROVED** [review]
There were just a bunch of removed lines, most from `setup.py` which shouldn't break much. And the tests pass, which is great.

**Comment by dnadeau4** [comment]
The line in setup.py was creating the file "git.py" on-the-fly which is not used and no longer needed since we have versioning with conda.

**Pull request merged**
